### ISSUE TITLE
how to access the database?

### ISSUE THREAD

**Issue by Kirushikesh** [rohitsakala/synopsisDebateParser#1]
As mentioned in the paper the database is stored in MongoDB. Can you please explain how to access the stored data using python?

**Comment by rohitsuse** [comment]
Can't be accessed. please re-run the codes and populate in your local MongoDB

**Comment by Kirushikesh** [comment]
Some files were missing cannot able to replicate the database
`from models import MatterUnderThreeSevenSeven #models not found` from debateTypePopulate.py

Can you also please mention step-by-step instructions to run this repository? Thanks
